name = "temp-email"
main = "src/worker.ts"
compatibility_date = "2025-04-01"
compatibility_flags = [ "nodejs_compat" ]
keep_vars = true

[triggers]
crons = [ "0 0 * * *" ]

[[d1_databases]]
binding = "DB"
database_name = "ffz1"
database_id = "67f878d2-36d5-450e-bddb-06e56b88d08b"

[vars]
DOMAINS = ["amaledaiern.net","creative-brackets.marketing","aokmsealire.com","fiesmilairevri.com","gmaalrapide.com","haseumtrre.com"]
ADMIN_PASSWORDS = ["123"]
ENABLE_USER_CREATE_EMAIL = true
ENABLE_USER_DELETE_EMAIL = true
JWT_SECRET = "my-super-secret-jwt-key-change-this"
PREFIX = "tmp"
